project:
  type: website

website:
  page-navigation: true
  title: "STA 210 - Spring 2025"
  description: "Homepage for STA 210 - Regression Analysis at Duke University"
  site-url: https://sta210-sp25.netlify.app

  repo-url: https://github.com/sta210-sp25/website
  repo-actions: [issue]
  
  page-footer:
    background: "#338EA0"
    left: |
      &copy; Copyright 2025, Maria Tackett
    right: |
      This site is built with [Quarto](https://quarto.org/)

  sidebar:
    background: "#338EA0"
    logo: "images/logo.png"
    align: center
    tools: 
      - icon: github
        href: https://github.com/sta210-sp25
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: chat-dots-fill
        href: https://edstem.org/us/courses/70992/discussion/
      - icon: check-square-fill
        menu:
          - text: Canvas
            url: https://canvas.duke.edu/courses/47067
          - text: Gradescope
            url: https://www.gradescope.com/courses/938130
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: overview.qmd
        text: Overview
      - href: syllabus.qmd
        text: Syllabus
      - href: support.qmd
        text: Support
      - href: index.qmd
        text: Schedule 
      - section: Computing
        contents: 
        - href: computing-access.qmd
          text: Access
        - href: computing-troubleshooting.qmd
          text: Troubleshooting
        - href: computing-r-resources.qmd
          text: R resources
      - section: Homework
        contents:
        - href: hw/hw-01.qmd
          text: HW 01
        - href: hw/hw-02.qmd
          text: HW 02
        - href: hw/hw-03.qmd
          text: HW 03
        - href: hw/hw-04.qmd
          text: HW 04
        - href: hw/hw-05.qmd
          text: HW 05
        - href: hw/stats-experience.qmd
          text: Statistics experience
      - section: Labs
        contents: 
        - href: labs/lab-00.qmd
          text: Lab 00
        - href: labs/lab-01.qmd
          text: Lab 01
        - href: labs/lab-02.qmd
          text: Lab 02
        - href: labs/lab-03.qmd
          text: Lab 03
        - href: labs/lab-04.qmd
          text: Lab 04
        - href: labs/lab-05.qmd
          text: Lab 05
        - href: labs/lab-06.qmd
          text: Lab 06
      - section: Project
        contents:
        - href: project.qmd
          text: Instructions
        - href: project-tips.qmd
          text: Tips + resources
      - href: links.qmd
        text: Useful links
      - href: https://forms.office.com/r/RPkWfBB4vf
        text: Lecture recording request
     # - href: https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=347eba5e-3c22-4926-8731-b25e0125ae4f
      #  text: Lecture recordings
        

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: visual    
    



