project:
  type: website

website:
  page-navigation: true
  title: "STA 210 - Fall 2023"
  description: "Homepage for STA 210 - Regression Analysis at Duke University, Fall 2023"
  site-url: https://sta210-fa23.netlify.app

  repo-url: https://github.com/sta210-fa23/website
  repo-actions: [edit, issue]
  
  page-footer:
    background: "#7eb7c2"
    left: |
      &copy; Copyright 2022, Maria Tackett
    right: |
      This site is built with [Quarto](https://quarto.org/)

  sidebar:
    background: "#7eb7c2"
    logo: "images/logo.png"
    align: center
    tools: 
      - icon: github
        href: https://github.com/sta210-fa23
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: person-fill
        text: "Sakai"
        menu:
          - text: Sakai
            url: https://sakai.duke.edu/portal/site/f2e8b7dc-61e6-4431-9b5c-29f8411ee5db
          - text: Ed Discussion 
            url: https://edstem.org/us/courses/44523/discussion/
          - text: Gradescope 
            url: https://www.gradescope.com/courses/584312
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: schedule.qmd
        text: Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: support.qmd
        text: Support
      - href: links.qmd
        text: Useful links
      - section: Computing
        contents: 
        - href: computing-access.qmd
          text: Access
        - href: computing-troubleshooting.qmd
          text: Troubleshooting
        - href: computing-r-resources.qmd
          text: R resources
      - section: Project
        contents:
        - href: project.qmd
          text: Instructions
        - href: project-tips.qmd
          text: Tips + resources
      - href: stats-experience.qmd
        text: Statistics experience
      - href: https://docs.google.com/spreadsheets/d/1dUD4SOpM79BL2kdvue9I2TP-ibcdxfpOIkHkMreYx64/edit?usp=sharing
        text: Lecture recordings

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: visual    
    



