---
title: "Lab 04"
subtitle: "Expanding multiple linear regression"
date: "2025-03-03"
date-format: "MMM DD, YYYY"
footer: "[🔗 STA 210 - Spring 2025](https://sta210-sp25.netlify.app)"
logo: "../images/logo.png"
format: 
  revealjs: 
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    include-before: [ '<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

## Goals

-   Project

-   Mid-semester survey

-   Lab 05: Expanding multiple linear regression

## Final project

-   Feedback on your project proposal is posted as an Issue in your project repo

-   Please let your lab TA know if you have any questions

-   Next milestone: [Exploratory Data Analysis](../project#eda) due March 20

    -   Time to work on it in next lab

## Mid-semester feedback 

-   **Purpose**: To give the teaching team feedback on what is working well (or not as well) in helping you learn the course content

-   The feedback is **anonymous** and will not be graded

-   It will be available until Thursday, March 6 at 11:59pm

    -   Please take a few minutes to fill it out during lab today

🔗 <https://duke.qualtrics.com/jfe/form/SV_eJKzmGyGpSPNQai>

**We (the teaching team) appreciate your feedback!**

## Today's lab

This lab focuses on

-   modeling complex data using variable transformations, categorical predictors and interactions, and various model specifications.

-   evaluating model diagnostics and conditions.

🔗 <https://sta210-sp25.netlify.app/labs/lab-04>
