{
  "hash": "ead47594b8bd877c30e53bb6ccc8726f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multinomial Logistic Regression\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2025-04-03\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 210 - Spring 2025](https://sta210-sp25.netlify.app)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 21-multinomial-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n\n\n\n## Topics\n\n::: nonincremental\n-   Conditions for logistic regression AE\n\n-   Multinomial logistic regression\n\n-   Interpret model coefficients\n\n-   Inference for a coefficient $\\beta_{jk}$\n:::\n\n## Computational setup\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(NHANES) #data set\nlibrary(knitr)\nlibrary(patchwork)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 20))\n```\n:::\n\n\n\n\n# Generalized Linear Models\n\n## Generalized Linear Models (GLMs) {.smaller}\n\n-   In practice, there are many different types of outcome variables:\n\n    ::: nonincremental\n    -   **Continuous:** Price of house\n    -   **Binary**: Win or Lose\n    -   **Nominal**: Democrat, Republican or Third Party candidate\n    -   **Ordered**: Movie rating (1 - 5 stars)\n    -   and others...\n    :::\n\n-   Predicting each of these outcomes requires a **generalized linear model**, a broader class of models that *generalize* the multiple linear regression model\n\n::: callout-note\nRecommended reading for more details about GLMs: [*Generalized Linear Models: A Unifying Theory*](https://bookdown.org/roback/bookdown-bysh/ch-glms.html).\n:::\n\n## Binary outcome (Logistic)\n\n-   Given $P(y_i=1|x_i)= \\hat{p}_i\\hspace{5mm} \\text{ and } \\hspace{5mm}P(y_i=0|x_i) = 1-\\hat{p}_i$\n\n    $$\n    \\log\\Big(\\frac{\\hat{p}_i}{1-\\hat{p}_i}\\Big) = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i} + \\dots \\hat{\\beta}_px_p\n    $$\n\n-   We can calculate $\\hat{p}_i$ by solving the logit equation:\n\n    $$\n    \\hat{p}_i = \\frac{\\exp\\{\\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i} + \\dots +\\hat{\\beta}_px_p\\}}{1 + \\exp\\{\\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i} + \\dots +\\hat{\\beta}_px_p\\}}\n    $$\n\n## Binary outcome (Logistic) {.smaller}\n\n::: incremental\n-   Suppose we consider $y=0$ the **baseline category** such that\n\n    $$\n    P(y_i=1|x_i) = \\hat{p}_{i1} \\hspace{2mm}  \\text{ and } \\hspace{2mm} P(y_i=0|x_i) = \\hat{p}_{i0}\n    $$\n\n-   Then the logistic regression model is\n\n    $$\n    \\log\\bigg(\\frac{\\hat{p}_{i1}}{1- \\hat{p}_{i1}}\\bigg) = \\log\\bigg(\\frac{\\hat{p}_{i1}}{\\hat{p}_{i0}}\\bigg) = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i1} + \\dots \\hat{\\beta}_px_{ip}\n    $$\n\n-   **Slope**, $\\hat{\\beta}_j$: When $x$ increases by one unit, the odds of $y=1$ versus the baseline $y=0$ are expected to multiply by a factor of $\\exp\\{\\hat{\\beta}_j\\}$\n\n-   **Intercept**, $\\hat{\\beta}_0$: When $x=0$, the predicted odds of $y=1$ versus the baseline $y=0$ are $\\exp\\{\\hat{\\beta}_0\\}$\n:::\n\n## Multinomial outcome variable\n\n-   Suppose the outcome variable $y$ is categorical and can take values $1, 2, \\ldots, K$ such that $(K > 2)$\n\n-   **Multinomial Distribution:**\n\n    $$\n    P(y=1) = p_1, P(y=2) = p_2, \\ldots, P(y=K) = p_K\n    $$\n\n    such that $\\sum\\limits_{k=1}^{K} p_k = 1$\n\n## Multinomial Logistic Regression {.small}\n\n::: incremental\n-   If we have an predictor variables $x_1, \\ldots, x_p$, then we want to fit a model such that $P(y = k) = p_k$ is a function of $x_1, \\ldots,x_p$\n\n-   Choose a baseline category. Let's choose $y=1$. Then,\n\n    $$\n    \\log\\bigg(\\frac{p_{ik}}{p_{i1}}\\bigg) = \\beta_{0k} + \\beta_{1k} x_{i1} + \\dots + \\beta_{pk}x_{ip}\n    $$\n\n-   In the multinomial logistic model, we have a separate equation for each category of the outcome relative to the baseline category\n\n    -   If the outcome has $K$ possible categories, there will be $K-1$ equations as part of the multinomial logistic model\n:::\n\n## Multinomial Logistic Regression\n\n-   Suppose we have a outcome variable $y$ that can take three possible outcomes that are coded as \"A\", \"B\", \"C\"\n\n-   Let \"A\" be the baseline category. Then\n\n    $$\n    \\begin{aligned}\n    \\log\\bigg(\\frac{p_{iB}}{p_{iA}}\\bigg) &= \\beta_{0B} + \\beta_{1B}x_{i1} + \\dots \\beta_{pB}x_{ip} \\\\[10pt]\n    \\log\\bigg(\\frac{p_{iC}}{p_{iA}}\\bigg) &= \\beta_{0C} + \\beta_{1C} x_{i1} + \\dots +\\beta_{pC}x_{ip}\n    \\end{aligned}\n    $$\n\n# Data\n\n## NHANES Data\n\n-   [National Health and ](https://www.cdc.gov/nchs/nhanes/?CDC_AAref_Val=https://www.cdc.gov/nchs/nhanes/index.htm)[Nutrition](https://www.cdc.gov/nchs/nhanes/?CDC_AAref_Val=https://www.cdc.gov/nchs/nhanes/index.htm)[ Examination Survey](https://www.cdc.gov/nchs/nhanes/?CDC_AAref_Val=https://www.cdc.gov/nchs/nhanes/index.htm) is conducted by the National Center for Health Statistics (NCHS)\n\n-   The goal is to *\"assess the health and nutritional status of adults and children in the United States\"*\n\n-   This survey includes an interview and a physical examination\n\n## NHANES Data\n\n-   We will use the data from the `NHANES` R package\n\n-   Contains 75 variables for the 2009 - 2010 and 2011 - 2012 sample years\n\n-   The data in this package is modified for educational purposes and should **not** be used for research\n\n-   Original data can be obtained from the [NCHS website](https://www.cdc.gov/nchs/data_access/index.htm) for research purposes\n\n-   Type `?NHANES` in console to see list of variables and definitions\n\n## Variables {.midi}\n\n**Goal:** Use a person's age and whether they do regular physical activity to predict their self-reported health rating.\n\n-   Outcome:\n\n    -   `HealthGen`: Self-reported rating of participant's health in general. Excellent, Vgood, Good, Fair, or Poor.\n\n-   Predictors:\n\n    -   `Age`: Age at time of screening (in years). Participants 80 or older were recorded as 80.\n    -   `PhysActive`: Participant does moderate to vigorous-intensity sports, fitness or recreational activities.\n\n## The data\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnhanes_adult <- NHANES |>\n  filter(Age >= 18) |>\n  select(HealthGen, Age, PhysActive) |>\n  filter(!(is.na(HealthGen))) |>\n  mutate(obs_num = 1:n())\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglimpse(nhanes_adult)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 6,710\nColumns: 4\n$ HealthGen  <fct> Good, Good, Good, Good, Vgood, Vgood, Vgood, Vgood, Vgood, …\n$ Age        <int> 34, 34, 34, 49, 45, 45, 45, 66, 58, 54, 50, 33, 60, 56, 56,…\n$ PhysActive <fct> No, No, No, No, Yes, Yes, Yes, Yes, Yes, Yes, Yes, No, No, …\n$ obs_num    <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …\n```\n\n\n:::\n:::\n\n\n\n\n## Exploratory data analysis\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](21-multinomial_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n## Exploratory data analysis\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](21-multinomial_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n# Fitting a multinomial logistic regression model\n\n## Model in R\n\nUse the `multinom` function from the **nnet** R package\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(nnet)\nhealth_fit <- multinom(HealthGen ~ Age + PhysActive, \n                     data = nhanes_adult)\n```\n:::\n\n\n\n\n<br>\n\nUse code chunk option `#| results: hide` to suppress convergence output\n\n## Model result\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhealth_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nmultinom(formula = HealthGen ~ Age + PhysActive, data = nhanes_adult)\n\nCoefficients:\n      (Intercept)           Age PhysActiveYes\nVgood   1.2053460  0.0009101848    -0.3209047\nGood    1.9476261 -0.0023686122    -1.0014925\nFair    0.9145492  0.0030462534    -1.6454297\nPoor   -1.5211414  0.0221905681    -2.6556343\n\nResidual Deviance: 17588.88 \nAIC: 17612.88 \n```\n\n\n:::\n:::\n\n\n\n\n## Tidy model output\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(health_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 6\n   y.level term           estimate std.error statistic  p.value\n   <chr>   <chr>             <dbl>     <dbl>     <dbl>    <dbl>\n 1 Vgood   (Intercept)    1.21       0.145       8.33  8.42e-17\n 2 Vgood   Age            0.000910   0.00246     0.369 7.12e- 1\n 3 Vgood   PhysActiveYes -0.321      0.0929     -3.45  5.51e- 4\n 4 Good    (Intercept)    1.95       0.141      13.8   1.39e-43\n 5 Good    Age           -0.00237    0.00242    -0.977 3.29e- 1\n 6 Good    PhysActiveYes -1.00       0.0901    -11.1   1.00e-28\n 7 Fair    (Intercept)    0.915      0.164       5.57  2.61e- 8\n 8 Fair    Age            0.00305    0.00288     1.06  2.90e- 1\n 9 Fair    PhysActiveYes -1.65       0.107     -15.3   5.69e-53\n10 Poor    (Intercept)   -1.52       0.290      -5.24  1.62e- 7\n11 Poor    Age            0.0222     0.00491     4.52  6.11e- 6\n12 Poor    PhysActiveYes -2.66       0.236     -11.3   1.75e-29\n```\n\n\n:::\n:::\n\n\n\n\n## Tidy model output, with CI\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(health_fit, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 8\n   y.level term         estimate std.error statistic  p.value conf.low conf.high\n   <chr>   <chr>           <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n 1 Vgood   (Intercept)   1.21e+0   0.145       8.33  8.42e-17  0.922     1.49   \n 2 Vgood   Age           9.10e-4   0.00246     0.369 7.12e- 1 -0.00392   0.00574\n 3 Vgood   PhysActiveY… -3.21e-1   0.0929     -3.45  5.51e- 4 -0.503    -0.139  \n 4 Good    (Intercept)   1.95e+0   0.141      13.8   1.39e-43  1.67      2.22   \n 5 Good    Age          -2.37e-3   0.00242    -0.977 3.29e- 1 -0.00712   0.00238\n 6 Good    PhysActiveY… -1.00e+0   0.0901    -11.1   1.00e-28 -1.18     -0.825  \n 7 Fair    (Intercept)   9.15e-1   0.164       5.57  2.61e- 8  0.592     1.24   \n 8 Fair    Age           3.05e-3   0.00288     1.06  2.90e- 1 -0.00260   0.00869\n 9 Fair    PhysActiveY… -1.65e+0   0.107     -15.3   5.69e-53 -1.86     -1.43   \n10 Poor    (Intercept)  -1.52e+0   0.290      -5.24  1.62e- 7 -2.09     -0.952  \n11 Poor    Age           2.22e-2   0.00491     4.52  6.11e- 6  0.0126    0.0318 \n12 Poor    PhysActiveY… -2.66e+0   0.236     -11.3   1.75e-29 -3.12     -2.19   \n```\n\n\n:::\n:::\n\n\n\n\n## Neatly display model output {.smaller}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|y.level |term          | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-------|:-------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|Vgood   |(Intercept)   |    1.205|     0.145|     8.325|   0.000|    0.922|     1.489|\n|Vgood   |Age           |    0.001|     0.002|     0.369|   0.712|   -0.004|     0.006|\n|Vgood   |PhysActiveYes |   -0.321|     0.093|    -3.454|   0.001|   -0.503|    -0.139|\n|Good    |(Intercept)   |    1.948|     0.141|    13.844|   0.000|    1.672|     2.223|\n|Good    |Age           |   -0.002|     0.002|    -0.977|   0.329|   -0.007|     0.002|\n|Good    |PhysActiveYes |   -1.001|     0.090|   -11.120|   0.000|   -1.178|    -0.825|\n|Fair    |(Intercept)   |    0.915|     0.164|     5.566|   0.000|    0.592|     1.237|\n|Fair    |Age           |    0.003|     0.003|     1.058|   0.290|   -0.003|     0.009|\n|Fair    |PhysActiveYes |   -1.645|     0.107|   -15.319|   0.000|   -1.856|    -1.435|\n|Poor    |(Intercept)   |   -1.521|     0.290|    -5.238|   0.000|   -2.090|    -0.952|\n|Poor    |Age           |    0.022|     0.005|     4.522|   0.000|    0.013|     0.032|\n|Poor    |PhysActiveYes |   -2.656|     0.236|   -11.275|   0.000|   -3.117|    -2.194|\n\n\n:::\n:::\n\n\n\n\n## Fair vs. Excellent Health\n\nThe baseline category for the model is `Excellent`.\n\n. . .\n\nThe model equation for the log-odds a person rates themselves as having \"Fair\" health vs. \"Excellent\" is\n\n$$\n\\log\\Big(\\frac{\\hat{p}_{Fair}}{\\hat{p}_{Excellent}}\\Big) = 0.915  + 0.003 ~ \\text{age} - 1.645 ~ \\text{PhysActive}\n$$\n\n## Interpretations {.midi}\n\n$$\n\\log\\Big(\\frac{\\hat{p}_{Fair}}{\\hat{p}_{Excellent}}\\Big) = 0.915  + 0.003 ~ \\text{age} - 1.645 ~ \\text{PhysActive}\n$$\n\nFor each additional year in age, the odds a person rates themselves as having fair health versus excellent health are expected to multiply by 1.003 (exp(0.003)), holding physical activity constant.\n\n<br>\n\n. . .\n\nThe odds a person who does physical activity will rate themselves as having fair health versus excellent health are expected to be 0.193 (exp(-1.645)) times the odds for a person who doesn't do physical activity, holding age constant.\n\n## Interpretations\n\n$$\n\\log\\Big(\\frac{\\hat{p}_{Fair}}{\\hat{p}_{Excellent}}\\Big) = 0.915  + 0.003 ~ \\text{age} - 1.645 ~ \\text{PhysActive}\n$$\n\nThe odds a 0 year old person who doesn't do physical activity rates themselves as having fair health vs. excellent health are 2.497 (exp(0.915)).\n\n. . .\n\n::: callout-warning\n**Need to mean-center age for the intercept to have a meaningful interpretation!**\n:::\n\n## Practice\n\n:::::: columns\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|y.level |term          | estimate|\n|:-------|:-------------|--------:|\n|Vgood   |(Intercept)   |    1.205|\n|Vgood   |Age           |    0.001|\n|Vgood   |PhysActiveYes |   -0.321|\n|Good    |(Intercept)   |    1.948|\n|Good    |Age           |   -0.002|\n|Good    |PhysActiveYes |   -1.001|\n|Fair    |(Intercept)   |    0.915|\n|Fair    |Age           |    0.003|\n|Fair    |PhysActiveYes |   -1.645|\n|Poor    |(Intercept)   |   -1.521|\n|Poor    |Age           |    0.022|\n|Poor    |PhysActiveYes |   -2.656|\n\n\n:::\n:::\n\n\n\n:::\n\n:::: {.column width=\"50%\"}\n::: question\n-   Write the equation for Very good (`Vgood`) versus Excellent.\n\n-   Interpret `Age` in the context of the data.\n\n-   Interpret `PhysActiveYes` in the context of the data.\n:::\n::::\n::::::\n\n## Recap\n\n-   Introduce multinomial logistic regression\n\n-   Interpret model coefficients\n",
    "supporting": [
      "21-multinomial_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}